apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: platform-backstage-catalog
  description: Catálogo central de entidades do Backstage
spec:
  type: url
  targets:
    - ./org/guests.yaml
    - ./systems/payments-platform.yaml
    - ./kafka-topics/payments.transaction.authorized.v1.yaml
    - ./components/payment-service.yaml
    - ./components/anti-fraud-service.yaml
    - ./components/notification-service.yaml
