apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  description: Time exemplo responsável pelos serviços e tópicos de pagamentos
spec:
  type: team
  profile:
    displayName: Guests
  children: []
